DROP TABLE IF EXISTS deferreds CASCADE;
DROP TABLE IF EXISTS administrators;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS addresses;
CREATE TABLE categories(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  super_category_id BIGINT NULL REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE customers(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  address_id BIGINT,
  cart_id BIGINT,
  order_id BIGINT,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL,
  status VARCHAR(10) NOT NULL
);

CREATE TABLE administrators(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL,
  status VARCHAR(10) NOT NULL
);

CREATE TABLE carts(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE
);
CREATE TABLE addresses(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  country VARCHAR(50) NOT NULL,
  region VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  street VARCHAR(50) NOT NULL,
  house_number VARCHAR(50) NOT NULL,
  customer_id BIGINT  references customers(id) ON DELETE CASCADE
);

CREATE TABLE products(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  category_id BIGINT REFERENCES categories(id),
  description VARCHAR(255),
  brand VARCHAR(50),
  price INTEGER NOT NULL,
  units_left_in_warehouse INTEGER NOT NULL
);
CREATE TABLE orders(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  data TIMESTAMP NOT NULL
);

CREATE TABLE items(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  quantity INTEGER NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  cart_id BIGINT REFERENCES carts(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE
);
CREATE TABLE deferreds(
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  item_id BIGINT REFERENCES items(id) ON DELETE CASCADE
)
